{
 "title": "Metrics dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "TOP 5 Process Elapsed Time",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT\n  event_date AS \"time\",\n  process_name,\n  pid,\n  hostname,\n  value\nFROM metrics\nWHERE id_metric_type = 1\nORDER BY value DESC\nLIMIT 5"
    }
   ]
  },
  {
   "title": "TOP 5 Process RSS Memory",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT\n  event_date AS \"time\",\n  process_name,\n  pid,\n  hostname,\n  value\nFROM metrics\nWHERE id_metric_type = 2\nORDER BY value DESC\nLIMIT 5"
    }
   ]
  },
  {
   "title": "Metrics load",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  event_date AS \"time\",\n  value\nFROM node_load\nORDER BY 1"
    }
   ]
  }
 ]
}